### ISSUE TITLE
[Bug]Progress bar does not work when using two processes in a dual CPU core environment.

### ISSUE THREAD

**Issue by Initial-heart-1** [allenfrostline/pyNCMDUMP#7]
This may require further testing to show if the problem only occurs in dual CPU core environments. In particular, it will need to be investigated whether the problem can occur in environments where the number of CPU cores is greater than or equal to the number of processes in addition to dual CPU core environments.
I only have one server with dual CPU core, so I was unable to perform these tests.

**Comment by allenfrostline** [comment]
Progbar is disabled intentionally due to lack of support of tqdm progbar across multiple processes. FYI

**Comment by Initial-heart-1** [comment]
OK, understood.
